/*
 *
 *
 * Filename:		myproject.c
 * Date:		02/28/2019
 * Author:		Stephen Perkins
 * Email:		stephen.perkins@utdallas.edu
 * Version:		1.0
 * Copyright:		2019, All Rights Reserved
 *
 * Description:
 *
 *	Call the yylex() function generated by flex.
 */

#include <stdio.h>             /* needed for printf() */
#include "myproject.h"         /* needed for ENUM */


/* 
 * Manually insert prototype and extern declarations for the
 * stuff in the flex output file.
 */
int yylex(void);
extern char *yytext;


/* Just call the lexical scanner until we reach EOF */

int main()
{
  int token;
  
  token = yylex();

  while(token != 0)
    {
      printf("The Token has the integer value %d\n", token);
      printf("\tThis token corresponds to: ");

      switch(token)
	{
	case HASHTOKEN:
	  printf("HASH\n");
	  break;
	case COMMATOKEN:
	  printf("COMMA\n");
	  break;
	case DASHTOKEN:
	  printf("DASH\n");
	  break;
	case SRTOKEN:
	  printf("SR\n");
	  break;
	case JRTOKEN:
	  printf("JR\n");
	  break;
	case INTTOKEN:
	  printf("INTEGER\n");
	  printf("\tThe integer string was: %s\n", yytext);
	  break;
	case EOLTOKEN:
	  printf("End of Line\n");
	  break;
	case ROMANTOKEN:
	  printf("ROMAN NUMERAL");
	  printf("\tThe Roman numeral was %s\n", yytext);
	case NAME_INITIAL_TOKEN:
	  printf("NAME INITIAL TOKEN\n");
	  printf("\tThe token value is %s\n", yytext);
	case IDENTIFIERTOKEN:
	  printf("IDENTIFIER TOKEN\n");
	  printf("\tThe token value is %s\n", yytext);
	case NAMETOKEN:
	  printf("NAMETOKEN\n");
	  printf("\tThe token value is %s\n", yytext);
	default:
	  printf("UNKNOWN\n");
	}

      token = yylex();
    }
  
  printf("Done\n");
  return 0;
}
