#ifndef _MYPROJECT_H_
#define _MYPROJECT_H_
/*
 *
 *
 * Filename:		myproject.h
 * Date:		02/28/2019
 * Author:		Stephen Perkins
 * Email:		stephen.perkins@utdallas.edu
 * Version:		1.0
 * Copyright:		2019, All Rights Reserved
 *
 * Description:
 *
 *	Call the yylex() function generated by flex.
 */


/* Enumerate the tokens we will try to match.  Make sure to NOT have a token with value 0 */

enum {HASHTOKEN=1, DASHTOKEN, COMMATOKEN, INTTOKEN, JRTOKEN, SRTOKEN, ROMANTOKEN, NAME_INITIAL_TOKEN, IDENTIFIERTOKEN, NAMETOKEN, EOLTOKEN};


#endif /* _MYPROJECT_H_ */
